name: Framework CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2 # need to checkout more for git diff later to work

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: latest
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: pnpm

    - uses: actions/cache@v3
      name: Setup osnap chromium cache
      with:
        path: ~/osnap_chromium_*
        key: ${{ runner.os }}-osnap-chromium
        restore-keys: |
          ${{ runner.os }}-osnap-chromium

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: |
        pnpm build

    - name: Verify build against repo content
      run: |
        git diff --exit-code --compact-summary || (echo "::notice::generated assets differ, maybe forgot to run gulp?"; exit 1)

    - name: Test
      run: |
        pnpm run ci

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failed-snapshots
        path: |
          tests/snapshots/__diff__
          tests/snapshots/__updated__

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
